

services:
  frontend:
    image: madhavbohra09/trustwise-frontend:latest
    build: ./ai_analysis_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
  # The image name is trustwise_task_backend:latest
    image: madhavbohra09/trustwise-backend:latest
  # if image doesn't exists, build the backend from the Dockerfile in the ai_analysis_backend directory
    build: ./ai_analysis_backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DB_USER : "postgres"
      DB_PASSWORD : "postgres"
      DB_HOST : "db"
      DB_PORT : "5432"
      DB_NAME : "trustwise"
    env_file:
      - .env  # Loads only Hugging Face and Gemini API keys from the .env file
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
